import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#4B8562',
    padding: 20,
  },
  noRecursosText: {
    textAlign: 'center',
    color: '#FFFFFF',
    fontSize: 16,
    marginTop: 20,
  },
  title: {
    fontSize: 26,
    color: '#FFFFFF',
    fontFamily: 'JuliusSansOne',
    textAlign: 'left',
    marginTop: 50,
    marginBottom: 20,
  },
  subtitle: {
    fontSize: 16,
    color: '#FFFFFF',
    textAlign: 'left',
    marginBottom: 20,
  },
  avatar: {
    position: 'absolute',
    top: 60,
    right: 30,
    backgroundColor: '#2D6B46'
  },
  tabs: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: 10,
  },
  tab: {
    fontSize: 20,
    color: '#DADCE0',
    marginHorizontal: 10,
  },
  activeTab: {
    color: '#FFFFFF',
    borderBottomWidth: 2,
    borderBottomColor: '#FFFFFF',
  },
  contentContainer: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 30,
    marginVertical: 10,
  },
  contentContainer2: {
    paddingBottom: 60,
  },
  sectionTitle: {
    fontSize: 18,
    color: '#4B8562',
    marginTop: 20,
    marginBottom: 30,
    textAlign: 'center',
  },
  statusText: {
    fontSize: 14,
    fontWeight: '600',
  },
  input: {
    borderWidth: 1,
    width: '85%',
    backgroundColor: '#C3C3C3',
    borderColor: '#C3C3C3',
    color: '#FFFFFF',
    padding: 10,
    marginBottom: 30,
    borderRadius: 8,
  },
  image: {
    width: 100,
    height: 100,
    marginBottom: 25,
    borderRadius: 10,
    alignSelf: 'center',
    alignItems: 'center',
  },
  imageGestao: {
    width: 100,
    height: 100,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  button: {
    width: '70%',
    height: 50,
    backgroundColor: '#4B8562',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginBottom: 20,
    maxWidth: 300,
  },
  buttonText: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  card: {
    backgroundColor: '#F9F9F9',
    borderRadius: 10,
    padding: 30,
    marginVertical: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
    width: '100%',
    alignSelf: 'center',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#4B8562',
  },
  textContainer: {
    width: '100%',
    marginBottom: 10,
    alignSelf: 'center',
    alignItems: 'center',
  },
  cardTitleInput: {
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#DDD',
    width: '100%',
  },
  buttonContainer: {
    width: '70%',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  imageAndButtonsContainer: {
    width: '90%',
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    paddingHorizontal: 10,
  },
  updateButton: {
    width: '100%',
    backgroundColor: '#4B8562',
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: 5,
    maxWidth: 300,
  },
  deleteButton: {
    width: '100%',
    backgroundColor: '#D9534F',
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: 5,
    marginTop: 10,
    maxWidth: 300,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 25,
    backgroundColor: '#FFFFFF',
  },
  icons: {
    fontSize: 28,
    color: '#2D6B46',
  },
});

export default styles;
